# Generated by Django 6.0 on 2026-06-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0078_remove_questionnaire_tags_delete_questionnairetag'),
        ('lab_analyzer_device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmessage',
            name='diagnostic_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_messages', to='emr.diagnosticreport'),
        ),
        migrations.AddField(
            model_name='labmessage',
            name='protocol',
            field=models.CharField(choices=[('hl7', 'HL7'), ('astm', 'ASTM')], default='hl7', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labmessage',
            name='message_type',
            field=models.CharField(choices=[('ORM', 'Order Message'), ('ORU', 'Observation Result'), ('QRY', 'Query'), ('DSP', 'Worklist Response')], max_length=10),
        ),
        migrations.AlterField(
            model_name='labmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('acknowledged', 'Acknowledged'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('error', 'Error')], default='received', max_length=20),
        ),
    ]
